### PR TITLE
Support HammerDB architecture with Azure Virtual Machines

### PR DESCRIPTION
**Pull request by mw2q**
Add additional resources to the terraform scripts so that a dedicated system for running HammerDB can be provisioned to run the TPROC-C workload.

### CODE REVIEW

**Review by jt-edb — COMMENTED** [review]
LGTM.

Just one thing: since this commit https://github.com/EnterpriseDB/postgres-deployment/commit/c0c8575bf3b7b377f4fe4b1a9ddd6782d221140d the HammerDB-TPROC-C ref. architecture is not available for azure and gcloud.
I'd suggest to define a new Option class dedicated to azure, like this one for AWS: https://github.com/EnterpriseDB/postgres-deployment/blob/master/edbdeploy/options.py#L22-L35

**Comment by vibhorkumar123** [comment]
@mw2q Can you please look at the above comment from @jt-edb ?
Thank you!

**Comment by mw2q** [comment]
> @mw2q Can you please look at the above comment from @jt-edb ?
> Thank you!

Yes, only just got to it...

**Review by jt-edb — APPROVED** [review]
LGTM

**Pull request merged**
