### PR TITLE
Extract cloud specific code from project.py

### PR DESCRIPTION
**Pull request by jt-edb**
Specific code of cloud vendor is now located in multiple classes
inheriting from Project class.

2 ways for executing specific code:
  1. Classic method overloading.
  2. Code injection using a new hook mechanism.

### CODE REVIEW

**Comment by jt-edb** [comment]
Tests:
- [ ] AWS
- [ ] azure
- [ ] gcloud
- [ ] baremetal
- [ ] vmware
- [ ] AWS RDS
- [ ] AWS RDS Aurora
- [ ] AzureDB

**Comment by mw2q** [comment]
> Tests with `configure`, `provision`, `deploy`, `display`, `passwords`, `list`, `destroy` and `remove`:
>     * [ ]  gcloud
>       
>       * [x]  configure
>       * [ ]  provision fails with the following terraform error: `Error: Error creating Network: googleapi: Error 403: Required 'compute.networks.create' permission for 'projects/performance-engineering-268015/global/networks/test-edb-network', forbidden`

I wasn't able to reproduce the error.  All these commands work successfully for me on 12bc9d89faf5bcfd26e660d51e96ae2ad72bf0ac .

**Comment by mw2q** [comment]
Submitted fixes for AWS RDS: https://github.com/jt-edb/postgres-deployment/pull/1

**Comment by mw2q** [comment]
The azuredb commands all seems to work except `deploy` and it appear to be because of an RHEL8 issue identified in this issue tracker: https://github.com/ComplianceAsCode/content/issues/7016

**Pull request merged**
